### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by orbitaldecay** [civboot/fngi#20]
Looks like the build is broken as of 4ac70a80055ae522a4bef4c991268860eb4bf028. See comment on commit. I am able to build with the parent (2280a690acbdc43a1866751436b7ec324b838d65) and the latest versions of zoa, cxt, and civc as of now.

**Comment by vitiral** [comment]
Sorry, forgot to push civc dev branch to main. Should be fixed now.

**Comment by vitiral** [comment]
Civc commit: 36f406e
